openapi: 3.1.0
info:
  title: Auth Service
  description: Authentication and authorization service for Educesol platform
  version: 0.0.0
tags:
  - name: Authentication
paths:
  /api/auth/histories:
    get:
      operationId: Auth_histories
      description: Get all login histories (requires authentication)
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginHistoriesResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Authentication
  /api/auth/histories/{id}:
    get:
      operationId: Auth_getUserLoginHistories
      description: Get login histories for a specific user (requires authentication)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserLoginHistoriesResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Authentication
  /api/auth/logout:
    post:
      operationId: Auth_logout
      description: Logout user and blacklist refresh token
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogoutResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Authentication
  /api/auth/signin:
    post:
      operationId: Auth_signin
      description: Authenticate user and get tokens
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SigninResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SigninRequest'
  /api/auth/signup:
    post:
      operationId: Auth_signup
      description: Register a new user
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignupResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
  /api/auth/token:
    post:
      operationId: Auth_token
      description: Renew access token using refresh token
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenewTokenResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Authentication
components:
  schemas:
    ErrorResponse:
      type: object
      required:
        - success
        - message
      properties:
        success:
          type: boolean
        message:
          type: string
        code:
          type: integer
          format: int32
    Gender:
      type: string
      enum:
        - M
        - F
    LoginHistoriesResponse:
      type: object
      required:
        - data
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/LoginHistory'
      allOf:
        - $ref: '#/components/schemas/SuccessResponse'
    LoginHistory:
      type: object
      required:
        - id
        - ipAddress
        - device
        - userId
        - createdOn
      properties:
        id:
          type: string
        ipAddress:
          type: string
        device:
          type: string
        userId:
          type: string
        createdOn:
          type: string
    LogoutResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/SuccessResponse'
    RenewTokenResponse:
      type: object
      required:
        - accessToken
      properties:
        accessToken:
          type: string
      allOf:
        - $ref: '#/components/schemas/SuccessResponse'
    SigninRequest:
      type: object
      required:
        - password
      properties:
        email:
          type: string
        phone:
          type: string
        password:
          type: string
    SigninResponse:
      type: object
      required:
        - tokens
      properties:
        tokens:
          $ref: '#/components/schemas/TokenResponse'
      allOf:
        - $ref: '#/components/schemas/SuccessResponse'
    SignupRequest:
      type: object
      required:
        - email
        - user_type
        - first_name
        - last_name
        - phone
        - password
        - profile
      properties:
        email:
          type: string
        user_type:
          $ref: '#/components/schemas/UserRole'
        first_name:
          type: string
        last_name:
          type: string
        middle_name:
          type: string
        phone:
          type: string
        password:
          type: string
        profile:
          $ref: '#/components/schemas/UserProfile'
    SignupResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/SuccessResponse'
    SuccessResponse:
      type: object
      required:
        - success
        - message
      properties:
        success:
          type: boolean
        message:
          type: string
    TokenResponse:
      type: object
      required:
        - accessToken
        - refreshToken
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
    UserLoginHistoriesResponse:
      type: object
      required:
        - data
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/LoginHistory'
      allOf:
        - $ref: '#/components/schemas/SuccessResponse'
    UserProfile:
      type: object
      required:
        - date_of_birth
        - gender
        - medical_conditions
        - school_id
      properties:
        date_of_birth:
          type: string
        gender:
          $ref: '#/components/schemas/Gender'
        medical_conditions:
          type: string
        school_id:
          type: string
    UserRole:
      type: string
      enum:
        - TEACHER
        - STUDENT
        - GUARDIAN
servers:
  - url: https://auth-service-ms-app.fly.dev/
    description: Server Root Endpoint
    variables: {}