import type { Metadata } from 'next';
import { poppins } from '@/app/ui/fonts';
import './globals.css';
import { AuthProvider } from './contexts/AuthContext';
// import EnvironmentCheck from './components/EnvironmentCheck';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <AuthProvider>
          {children}
          {/* <EnvironmentCheck /> */}
        </AuthProvider>
      </body>
    </html>
  );
}
